#!/bin/bash
if [ "$2" = "" ]; then echo "$0 file.pts startframe"; exit; fi
stf=$2

echo "creating tstamps.csv"
(
read -r line
read -r line
o=$((`echo $line | sed "s/\.//g"`))
echo ",$o"
while read -r line
do
  u=$((`echo $line | sed "s/\.//g"`))
  echo $(($u - $o)),$u
  o=$u
done
) <$1 >tstamps.csv

us=`cut -f1 -d, tstamps.csv | sort -n | uniq -c | sort -n | tail -1 | cut -b9-`
l=$((`wc --lines tstamps.csv | cut -f1 -d\ ` - $stf))
fps=$((1000000 / $us)) 
echo "$l frames were captured at ${fps}fps" 
stf=$(($stf + 1 + 3))

echo "frame delta time[us] distribution"
tail -n +$stf tstamps.csv | cut -f1 -d, | sort -n | uniq -c

D=`echo "0123456789" | sed "s/\`echo $((1000000/$fps)) | cut -b1\`//"`

echo "after skip frame indices (middle column)"
tail -n +$stf tstamps.csv | grep "^[$D]" | sed "s/^/> /"

skips=`tail tstamps.csv -n +$stf | grep "^[$D]" | wc --lines | cut -f1 -d\ `
stamps=`tail tstamps.csv -n +$stf | wc --lines | cut -f1 -d\ `
per=`expr \( 100 \* $skips \) / \( $skips + $stamps \)`
echo "$skips frame skips ($per%)"
